// <auto-generated />
namespace LaMiaApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ModificataAppuntamento_RimossoTitolo_Obbligatorio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModificataAppuntamento_RimossoTitolo_Obbligatorio));
        
        string IMigrationMetadata.Id
        {
            get { return "201804181659077_ModificataAppuntamento_RimossoTitolo_Obbligatorio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
